name: "Tests"

on:
  [ push, pull_request ]

jobs:

  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: docker-compose
        run: docker-compose -f ../.actions-docker-compose.yml up -d

      - name: cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('server/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-

      - name: pip install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r dev-requirements.txt

      - name: pytest
        run: pytest --disable-pytest-warnings --cov=./

      - name: behave
        run: behave --format progress2 --logging-level=ERROR


  client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install
        run: npm install

      - name: build
        run: npm run build
