name: "Tests"

permissions:
  contents: read
  pull-requests: write

on:
  [ push, pull_request ]

jobs:

  server:
    uses: superdesk/newsroom-app/.github/workflows/server.yml@develop

  pytest:
    uses: superdesk/newsroom-app/.github/workflows/pytest.yml@develop

  client:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['22']
    uses: superdesk/newsroom-app/.github/workflows/client.yml@develop
    with:
      node-version: ${{ matrix.node-version }}
