name: "Tests"

on:
  [ push, pull_request ]

jobs:

  server:
    uses: superdesk/newsroom-app/.github/workflows/server.yml@develop

  pytest:
    uses: superdesk/newsroom-app/.github/workflows/pytest.yml@develop

  behave:
    uses: superdesk/newsroom-app/.github/workflows/behave.yml@develop

  client:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['14', '22']
    uses: superdesk/newsroom-app/.github/workflows/client.yml@develop
    with:
      node-version: ${{ matrix.node-version }}
